-- TWICE Discography SQLite schema

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS albums (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  language TEXT NOT NULL,
  release_date TEXT NOT NULL,
  cover_local TEXT,
  cover_thumb_local TEXT,
  yt_video_id TEXT,
  bili_bvid TEXT,
  bili_page INTEGER DEFAULT 1,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_ja TEXT,
  name_ko TEXT,
  name_romanized TEXT,
  desc_zh TEXT,
  desc_en TEXT,
  desc_ja TEXT,
  desc_ko TEXT
);

CREATE TABLE IF NOT EXISTS tracks (
  id TEXT PRIMARY KEY,
  album_id TEXT REFERENCES albums(id) ON DELETE SET NULL,
  track_no INTEGER,
  duration_sec INTEGER,
  is_title INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL,
  member_ids_json TEXT,
  language TEXT,
  composer TEXT,
  lyricist TEXT,
  arranger TEXT,
  yt_video_id TEXT,
  bili_bvid TEXT,
  bili_page INTEGER DEFAULT 1,
  spotify_track_id TEXT,
  apple_music_id TEXT,
  apple_music_country TEXT,
  music_square_query TEXT,
  music_square_preferred TEXT,
  netease_song_id TEXT,
  qq_song_mid TEXT,
  title_zh TEXT NOT NULL,
  title_en TEXT NOT NULL,
  title_ja TEXT,
  title_ko TEXT,
  title_romanized TEXT,
  note_zh TEXT,
  note_en TEXT,
  note_ja TEXT,
  note_ko TEXT
);

CREATE TABLE IF NOT EXISTS members (
  id TEXT PRIMARY KEY,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_ja TEXT,
  name_ko TEXT,
  name_romanized TEXT,
  real_name_zh TEXT,
  real_name_en TEXT,
  real_name_ja TEXT,
  real_name_ko TEXT,
  birthday TEXT,
  nationality_code TEXT NOT NULL,
  flag_emoji TEXT NOT NULL,
  position_json TEXT,
  height_cm INTEGER,
  blood_type TEXT,
  mbti TEXT,
  zodiac TEXT,
  debut_date TEXT,
  color_hex TEXT,
  photo_local TEXT,
  photo_thumb_local TEXT,
  bio_zh TEXT,
  bio_en TEXT,
  bio_ja TEXT,
  bio_ko TEXT,
  instagram_handle TEXT,
  instagram_url TEXT
);

CREATE TABLE IF NOT EXISTS member_stories (
  id TEXT PRIMARY KEY,
  member_id TEXT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  order_no INTEGER NOT NULL,
  category TEXT NOT NULL,
  year INTEGER,
  title_zh TEXT NOT NULL,
  title_en TEXT,
  title_ja TEXT,
  title_ko TEXT,
  content_zh TEXT NOT NULL,
  content_en TEXT,
  content_ja TEXT,
  content_ko TEXT,
  source_url TEXT
);

CREATE TABLE IF NOT EXISTS cfs (
  id TEXT PRIMARY KEY,
  brand TEXT NOT NULL,
  brand_logo_local TEXT,
  year INTEGER,
  country TEXT,
  member_ids_json TEXT,
  song_title_zh TEXT NOT NULL,
  song_title_en TEXT,
  song_title_ja TEXT,
  song_title_ko TEXT,
  song_title_romanized TEXT,
  desc_zh TEXT,
  desc_en TEXT,
  desc_ja TEXT,
  desc_ko TEXT,
  yt_video_id TEXT,
  bili_bvid TEXT,
  bili_page INTEGER DEFAULT 1,
  thumb_local TEXT
);

CREATE TABLE IF NOT EXISTS covers (
  id TEXT PRIMARY KEY,
  performed_at TEXT NOT NULL,
  is_predebut INTEGER NOT NULL DEFAULT 0,
  original_artist TEXT,
  original_song TEXT NOT NULL,
  performer_member_ids_json TEXT,
  year INTEGER,
  language TEXT,
  yt_video_id TEXT,
  bili_bvid TEXT,
  bili_page INTEGER DEFAULT 1,
  thumb_local TEXT,
  note_zh TEXT,
  note_en TEXT,
  note_ja TEXT,
  note_ko TEXT
);
