export const albums = [
  {
    id: 'the-story-begins',
    type: 'mini',
    language: 'ko',
    release_date: '2015-10-20',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/63/0a/8b/630a8b70-f367-f5f4-1841-6c229313ebf8/00602508869884_Cover.jpg/1000x1000bb.jpg',
    name_zh: '故事开始',
    name_en: 'The Story Begins',
    name_ja: 'The Story Begins',
    name_ko: 'THE STORY BEGINS',
    name_romanized: 'The Story Begins',
    desc_zh: 'TWICE 出道迷你专辑，以 Like OOH-AHH 正式开启组合曲库。',
    desc_en: 'TWICE debut mini album led by Like OOH-AHH.',
    desc_ja: 'TWICE のデビューミニアルバム。',
    desc_ko: 'TWICE의 데뷔 미니 앨범.',
  },
  {
    id: 'page-two',
    type: 'mini',
    language: 'ko',
    release_date: '2016-04-25',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/7d/46/66/7d4666f3-1dec-c3ae-e81c-1efef0ae5d6b/00602508870033_Cover.jpg/1000x1000bb.jpg',
    name_zh: '第二页',
    name_en: 'Page Two',
    name_ja: 'Page Two',
    name_ko: 'PAGE TWO',
    name_romanized: 'Page Two',
    desc_zh: 'Cheer Up 所在专辑，确立 TWICE 明亮校园感。',
    desc_en: 'Home of Cheer Up, a breakout era for TWICE.',
    desc_ja: 'Cheer Up を収録したブレイク作。',
    desc_ko: 'Cheer Up이 수록된 대표 미니 앨범.',
  },
  {
    id: 'twicecoaster-lane-one',
    type: 'mini',
    language: 'ko',
    release_date: '2016-10-24',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/0e/c5/67/0ec5678b-9070-ac48-f01d-c8af72b92d01/00602508870064_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'TWICEcoaster: LANE 1',
    name_en: 'TWICEcoaster: LANE 1',
    name_ja: 'TWICEcoaster: LANE 1',
    name_ko: 'TWICEcoaster: LANE 1',
    name_romanized: 'TWICEcoaster Lane One',
    desc_zh: 'TT 所在专辑，延续 TWICE 代表性流行旋律。',
    desc_en: 'The TT era, one of the group’s signature releases.',
    desc_ja: 'TT を収録した代表作。',
    desc_ko: 'TT가 수록된 대표 앨범.',
  },
  {
    id: 'what-is-love',
    type: 'mini',
    language: 'ko',
    release_date: '2018-04-09',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/7e/41/69/7e4169e8-8358-27ff-66b4-1564ec800abd/00602508875137_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'What is Love?',
    name_en: 'What is Love?',
    name_ja: 'What is Love?',
    name_ko: 'What is Love?',
    name_romanized: 'What is Love',
    desc_zh: '以电影感概念包装“爱是什么”的代表迷你专辑。',
    desc_en: 'A film-inspired mini album asking what love is.',
    desc_ja: '映画的なコンセプトで愛を描くミニアルバム。',
    desc_ko: '영화적인 콘셉트로 사랑을 묻는 미니 앨범.',
  },
  {
    id: 'fancy-you',
    type: 'mini',
    language: 'ko',
    release_date: '2019-04-22',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/03/76/e6/0376e6f9-f6d8-68f7-ae85-1a4ef17002aa/00602508875229_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'FANCY YOU',
    name_en: 'FANCY YOU',
    name_ja: 'FANCY YOU',
    name_ko: 'FANCY YOU',
    name_romanized: 'Fancy You',
    desc_zh: 'FANCY 开启更成熟的 TWICE 声音与视觉。',
    desc_en: 'FANCY introduced a sleeker, more mature TWICE sound.',
    desc_ja: 'より成熟した TWICE サウンドを見せた作品。',
    desc_ko: '한층 성숙한 TWICE의 사운드를 보여 준 앨범.',
  },
  {
    id: 'eyes-wide-open',
    type: 'album',
    language: 'ko',
    release_date: '2020-10-26',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/1f/46/44/1f46442a-ed5a-7cc8-c119-c6453b559ef7/192641580802_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'Eyes wide open',
    name_en: 'Eyes wide open',
    name_ja: 'Eyes wide open',
    name_ko: 'Eyes wide open',
    name_romanized: 'Eyes Wide Open',
    desc_zh: '第二张韩语正规专辑，包含 I CAN’T STOP ME。',
    desc_en: 'Second Korean studio album featuring I CAN’T STOP ME.',
    desc_ja: 'I CAN’T STOP ME を収録した韓国2枚目のフルアルバム。',
    desc_ko: 'I CAN’T STOP ME가 수록된 두 번째 정규 앨범.',
  },
  {
    id: 'formula-of-love',
    type: 'album',
    language: 'ko',
    release_date: '2021-11-12',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/87/f5/e0/87f5e0de-c909-f4e6-9621-123565dfbc80/738676858440_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'Formula of Love: O+T=<3',
    name_en: 'Formula of Love: O+T=<3',
    name_ja: 'Formula of Love: O+T=<3',
    name_ko: 'Formula of Love: O+T=<3',
    name_romanized: 'Formula of Love',
    desc_zh: '第三张韩语正规专辑，收录 The Feels 韩文版等多样曲风。',
    desc_en: 'Third Korean studio album with a broad pop palette.',
    desc_ja: '多彩なポップサウンドを収録した韓国3枚目のフルアルバム。',
    desc_ko: '다채로운 팝 사운드가 담긴 세 번째 정규 앨범.',
  },
  {
    id: 'ready-to-be',
    type: 'mini',
    language: 'ko',
    release_date: '2023-03-10',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/8c/cf/96/8ccf96fa-afa3-c039-6e33-d19ae58ae074/738676860610_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'READY TO BE',
    name_en: 'READY TO BE',
    name_ja: 'READY TO BE',
    name_ko: 'READY TO BE',
    name_romanized: 'Ready To Be',
    desc_zh: '包含 SET ME FREE 的迷你专辑，强调更主动的舞台能量。',
    desc_en: 'Mini album led by SET ME FREE.',
    desc_ja: 'SET ME FREE を収録したミニアルバム。',
    desc_ko: 'SET ME FREE가 수록된 미니 앨범.',
  },
  {
    id: 'strategy',
    type: 'mini',
    language: 'ko',
    release_date: '2024-12-06',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/d3/65/0c/d3650c39-d01d-2453-6826-9aa21ad22559/8809928952925_Cover.jpg/1000x1000bb.jpg',
    name_zh: 'STRATEGY',
    name_en: 'STRATEGY',
    name_ja: 'STRATEGY',
    name_ko: 'STRATEGY',
    name_romanized: 'Strategy',
    desc_zh: '近期代表发行，收录 Strategy。',
    desc_en: 'Recent representative release featuring Strategy.',
    desc_ja: 'Strategy を収録した近年の代表作。',
    desc_ko: 'Strategy가 수록된 최근 대표작.',
  },
  {
    id: 'misamo-masterpiece',
    type: 'unit',
    language: 'ja',
    release_date: '2023-07-26',
    cover_local: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/0d/2e/8c/0d2e8c6e-49a6-25e7-f72c-3b2e3d7a96e5/5054197717185.jpg/1000x1000bb.jpg',
    name_zh: 'Masterpiece',
    name_en: 'Masterpiece',
    name_ja: 'Masterpiece',
    name_ko: 'Masterpiece',
    name_romanized: 'Masterpiece',
    desc_zh: 'MISAMO 日本小分队出道作品。',
    desc_en: 'MISAMO’s Japanese unit debut release.',
    desc_ja: 'MISAMO の日本ユニットデビュー作。',
    desc_ko: 'MISAMO의 일본 유닛 데뷔작.',
  },
]

export const tracks = [
  {
    id: 'like-ooh-ahh',
    album_id: 'the-story-begins',
    track_no: 1,
    duration_sec: 215,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE Like OOH-AHH',
    music_square_preferred: 'qq',
    title_zh: 'Like OOH-AHH',
    title_en: 'Like OOH-AHH',
    title_ja: 'Like OOH-AHH',
    title_ko: 'OOH-AHH하게',
    title_romanized: 'Ooh-Ahh Hage',
    note_zh: '出道曲。',
    note_en: 'Debut title track.',
  },
  {
    id: 'cheer-up',
    album_id: 'page-two',
    track_no: 1,
    duration_sec: 208,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE Cheer Up',
    music_square_preferred: 'qq',
    title_zh: 'Cheer Up',
    title_en: 'Cheer Up',
    title_ja: 'Cheer Up',
    title_ko: 'CHEER UP',
    title_romanized: 'Cheer Up',
    note_zh: '代表性爆发曲。',
    note_en: 'Breakout hit.',
  },
  {
    id: 'tt',
    album_id: 'twicecoaster-lane-one',
    track_no: 1,
    duration_sec: 214,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE TT',
    music_square_preferred: 'qq',
    title_zh: 'TT',
    title_en: 'TT',
    title_ja: 'TT',
    title_ko: 'TT',
    title_romanized: 'TT',
    note_zh: '经典标题曲。',
    note_en: 'Classic title track.',
  },
  {
    id: 'what-is-love-track',
    album_id: 'what-is-love',
    track_no: 1,
    duration_sec: 208,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE What is Love',
    music_square_preferred: 'qq',
    netease_song_id: '551340976',
    qq_song_mid: '000UjWxp0xgBWS',
    title_zh: 'What is Love?',
    title_en: 'What is Love?',
    title_ja: 'What is Love?',
    title_ko: 'What is Love?',
    title_romanized: 'What is Love',
    note_zh: '电影感概念标题曲。',
    note_en: 'Film-inspired title track.',
  },
  {
    id: 'fancy',
    album_id: 'fancy-you',
    track_no: 1,
    duration_sec: 213,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE FANCY',
    music_square_preferred: 'qq',
    netease_song_id: '1360662681',
    qq_song_mid: '003Gjd8u1wDES5',
    kuwo_rid: '68432057',
    joox_song_mid: 'Z4EAEC122A5FD6',
    joox_song_id: '231629512',
    title_zh: 'FANCY',
    title_en: 'FANCY',
    title_ja: 'FANCY',
    title_ko: 'FANCY',
    title_romanized: 'Fancy',
    note_zh: '成熟路线代表曲。',
    note_en: 'A signature mature-era single.',
  },
  {
    id: 'feel-special',
    album_id: 'fancy-you',
    track_no: 2,
    duration_sec: 207,
    is_title: 0,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE Feel Special',
    music_square_preferred: 'qq',
    title_zh: 'Feel Special',
    title_en: 'Feel Special',
    title_ja: 'Feel Special',
    title_ko: 'Feel Special',
    title_romanized: 'Feel Special',
    note_zh: '歌迷高频收藏曲。',
    note_en: 'Fan-favorite single.',
  },
  {
    id: 'i-cant-stop-me',
    album_id: 'eyes-wide-open',
    track_no: 1,
    duration_sec: 205,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: "TWICE I CAN'T STOP ME",
    music_square_preferred: 'qq',
    title_zh: 'I CAN’T STOP ME',
    title_en: "I CAN'T STOP ME",
    title_ja: "I CAN'T STOP ME",
    title_ko: "I CAN'T STOP ME",
    title_romanized: "I Can't Stop Me",
    note_zh: '复古合成器流行标题曲。',
    note_en: 'Retro synth-pop title track.',
  },
  {
    id: 'the-feels',
    album_id: 'formula-of-love',
    track_no: 1,
    duration_sec: 198,
    is_title: 1,
    category: 'group',
    language: 'en',
    music_square_query: 'TWICE The Feels',
    music_square_preferred: 'qq',
    netease_song_id: '1883382643',
    qq_song_mid: '001f13El4TiDez',
    title_zh: 'The Feels',
    title_en: 'The Feels',
    title_ja: 'The Feels',
    title_ko: 'The Feels',
    title_romanized: 'The Feels',
    note_zh: '英文单曲代表。',
    note_en: 'Signature English single.',
  },
  {
    id: 'set-me-free',
    album_id: 'ready-to-be',
    track_no: 1,
    duration_sec: 181,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE SET ME FREE',
    music_square_preferred: 'qq',
    title_zh: 'SET ME FREE',
    title_en: 'SET ME FREE',
    title_ja: 'SET ME FREE',
    title_ko: 'SET ME FREE',
    title_romanized: 'Set Me Free',
    note_zh: 'READY TO BE 标题曲。',
    note_en: 'READY TO BE title track.',
  },
  {
    id: 'strategy-track',
    album_id: 'strategy',
    track_no: 1,
    duration_sec: 165,
    is_title: 1,
    category: 'group',
    language: 'ko',
    music_square_query: 'TWICE Strategy',
    music_square_preferred: 'qq',
    title_zh: 'Strategy',
    title_en: 'Strategy',
    title_ja: 'Strategy',
    title_ko: 'Strategy',
    title_romanized: 'Strategy',
    note_zh: '近期代表曲。',
    note_en: 'Recent representative title track.',
  },
  {
    id: 'pop-nayeon',
    album_id: null,
    track_no: null,
    duration_sec: 168,
    is_title: 1,
    category: 'solo',
    member_ids_json: '["nayeon"]',
    language: 'ko',
    music_square_query: 'NAYEON POP',
    music_square_preferred: 'qq',
    title_zh: 'POP!',
    title_en: 'POP!',
    title_ja: 'POP!',
    title_ko: 'POP!',
    title_romanized: 'Pop',
    note_zh: '娜琏 Solo 出道曲。',
    note_en: 'Nayeon solo debut single.',
  },
  {
    id: 'abcd-nayeon',
    album_id: null,
    track_no: null,
    duration_sec: 163,
    is_title: 1,
    category: 'solo',
    member_ids_json: '["nayeon"]',
    language: 'ko',
    music_square_query: 'NAYEON ABCD',
    music_square_preferred: 'qq',
    title_zh: 'ABCD',
    title_en: 'ABCD',
    title_ja: 'ABCD',
    title_ko: 'ABCD',
    title_romanized: 'ABCD',
    note_zh: '娜琏第二张 Solo 主打。',
    note_en: 'Nayeon second solo title track.',
  },
  {
    id: 'do-not-touch',
    album_id: 'misamo-masterpiece',
    track_no: 1,
    duration_sec: 185,
    is_title: 1,
    category: 'misamo',
    member_ids_json: '["mina","sana","momo"]',
    language: 'ja',
    music_square_query: 'MISAMO Do not touch',
    music_square_preferred: 'qq',
    title_zh: 'Do not touch',
    title_en: 'Do not touch',
    title_ja: 'Do not touch',
    title_ko: 'Do not touch',
    title_romanized: 'Do not touch',
    note_zh: 'MISAMO 代表曲。',
    note_en: 'MISAMO signature song.',
  },
  {
    id: 'hello-unit',
    album_id: 'formula-of-love',
    track_no: 2,
    duration_sec: 184,
    is_title: 0,
    category: 'unit',
    member_ids_json: '["nayeon","momo","chaeyoung"]',
    language: 'ko',
    music_square_query: 'TWICE HELLO NAYEON MOMO CHAEYOUNG',
    music_square_preferred: 'qq',
    title_zh: 'HELLO',
    title_en: 'HELLO',
    title_ja: 'HELLO',
    title_ko: 'HELLO',
    title_romanized: 'Hello',
    note_zh: '成员小分队曲。',
    note_en: 'Unit track by Nayeon, Momo and Chaeyoung.',
  },
  {
    id: 'i-love-you-more-than-anyone',
    album_id: null,
    track_no: null,
    duration_sec: 210,
    is_title: 0,
    category: 'cf',
    language: 'ko',
    music_square_query: 'TWICE I Love You More Than Anyone',
    music_square_preferred: 'qq',
    title_zh: 'I Love You More Than Anyone',
    title_en: 'I Love You More Than Anyone',
    title_ja: 'I Love You More Than Anyone',
    title_ko: '누구보다 널 사랑해',
    title_romanized: 'Nuguboda Neol Saranghae',
    note_zh: '广告/合作歌曲示例。',
    note_en: 'Advertising and collaboration song example.',
  },
  {
    id: 'greedy-cover',
    album_id: null,
    track_no: null,
    duration_sec: 190,
    is_title: 0,
    category: 'cover',
    member_ids_json: '["nayeon","momo","sana","mina","dahyun","chaeyoung","tzuyu"]',
    language: 'en',
    music_square_query: 'TWICE Greedy cover',
    music_square_preferred: 'qq',
    title_zh: 'Greedy',
    title_en: 'Greedy',
    title_ja: 'Greedy',
    title_ko: 'Greedy',
    title_romanized: 'Greedy',
    note_zh: '翻唱/舞台曲示例。',
    note_en: 'Cover stage example.',
  },
  {
    id: 'predebut-truth',
    album_id: null,
    track_no: null,
    duration_sec: 190,
    is_title: 0,
    category: 'predebut',
    language: 'ko',
    music_square_query: 'TWICE Truth',
    music_square_preferred: 'qq',
    title_zh: 'Truth',
    title_en: 'Truth',
    title_ja: 'Truth',
    title_ko: 'Truth',
    title_romanized: 'Truth',
    note_zh: '预出道/早期曲库占位示例。',
    note_en: 'Pre-debut and early catalog example.',
  },
]

export const members = [
  ['nayeon', '娜琏', 'Nayeon', 'ナヨン', '나연', 'Im Nayeon', '1995-09-22', 'KR', '🇰🇷', '#7dd3fc', '主唱 / 领舞 / 门面'],
  ['jeongyeon', '定延', 'Jeongyeon', 'ジョンヨン', '정연', 'Yoo Jeongyeon', '1996-11-01', 'KR', '🇰🇷', '#86efac', '主唱'],
  ['momo', '桃', 'Momo', 'モモ', '모모', 'Hirai Momo', '1996-11-09', 'JP', '🇯🇵', '#f9a8d4', '主舞 / 副唱'],
  ['sana', '纱夏', 'Sana', 'サナ', '사나', 'Minatozaki Sana', '1996-12-29', 'JP', '🇯🇵', '#f0abfc', '副唱'],
  ['jihyo', '志效', 'Jihyo', 'ジヒョ', '지효', 'Park Jihyo', '1997-02-01', 'KR', '🇰🇷', '#fde68a', '队长 / 主唱'],
  ['mina', '名井南', 'Mina', 'ミナ', '미나', 'Myoui Mina', '1997-03-24', 'JP', '🇯🇵', '#c4b5fd', '主舞 / 副唱'],
  ['dahyun', '多贤', 'Dahyun', 'ダヒョン', '다현', 'Kim Dahyun', '1998-05-28', 'KR', '🇰🇷', '#fca5a5', '领Rapper / 副唱'],
  ['chaeyoung', '彩瑛', 'Chaeyoung', 'チェヨン', '채영', 'Son Chaeyoung', '1999-04-23', 'KR', '🇰🇷', '#fdba74', '主Rapper / 副唱'],
  ['tzuyu', '子瑜', 'Tzuyu', 'ツウィ', '쯔위', 'Chou Tzuyu', '1999-06-14', 'CN', '🇨🇳', '#93c5fd', '门面 / 副唱 / 忙内'],
] as const

export const cfs = [
  {
    id: 'cf-i-love-you-more-than-anyone',
    brand: 'Collaboration Song',
    year: 2016,
    country: 'KR',
    song_title_zh: 'I Love You More Than Anyone',
    song_title_en: 'I Love You More Than Anyone',
    song_title_ja: 'I Love You More Than Anyone',
    song_title_ko: '누구보다 널 사랑해',
    desc_zh: '广告/合作歌曲分类示例，后续可继续补充品牌与物料。',
    desc_en: 'Advertising and collaboration song category example.',
  },
  {
    id: 'cf-pocari-sweat',
    brand: 'Pocari Sweat',
    year: 2017,
    country: 'KR',
    song_title_zh: 'Pocari Sweat Campaign',
    song_title_en: 'Pocari Sweat Campaign',
    song_title_ja: 'Pocari Sweat Campaign',
    song_title_ko: '포카리 스웨트 캠페인',
    desc_zh: 'TWICE 广告合作代表条目。',
    desc_en: 'Representative TWICE advertising collaboration.',
  },
]

export const covers = [
  {
    id: 'cover-greedy',
    performed_at: 'Special Stage',
    is_predebut: 0,
    original_artist: 'Ariana Grande',
    original_song: 'Greedy',
    performer_member_ids_json: '["nayeon","momo","sana","mina","dahyun","chaeyoung","tzuyu"]',
    year: 2018,
    language: 'en',
    note_zh: '舞台翻唱示例。',
    note_en: 'Cover stage example.',
  },
  {
    id: 'cover-truth-predebut',
    performed_at: 'Pre-debut Archive',
    is_predebut: 1,
    original_artist: 'TWICE',
    original_song: 'Truth',
    performer_member_ids_json: '["nayeon","jeongyeon","momo","sana","jihyo","mina","dahyun","chaeyoung","tzuyu"]',
    year: 2015,
    language: 'ko',
    note_zh: '预出道/早期曲库示例。',
    note_en: 'Pre-debut archive example.',
  },
]


